# Generated by Django 6.0.1 on 2026-01-10 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DearLastDigit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=50)),
                ('mor', models.CharField(max_length=1)),
                ('day', models.CharField(max_length=1)),
                ('evn', models.CharField(max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='DearLastThreeDigit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=50)),
                ('mor', models.CharField(max_length=1)),
                ('day', models.CharField(max_length=1)),
                ('evn', models.CharField(max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='DearLastTwoDigit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=50)),
                ('mor', models.CharField(max_length=1)),
                ('day', models.CharField(max_length=1)),
                ('evn', models.CharField(max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='SingaporeLastDigit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=50)),
                ('mor', models.CharField(max_length=1)),
                ('day', models.CharField(max_length=1)),
                ('evn', models.CharField(max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='SingaporeLastThreeDigit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=50)),
                ('mor', models.CharField(max_length=1)),
                ('day', models.CharField(max_length=1)),
                ('evn', models.CharField(max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='SingaporeLastTwoDigit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=50)),
                ('mor', models.CharField(max_length=1)),
                ('day', models.CharField(max_length=1)),
                ('evn', models.CharField(max_length=1)),
            ],
        ),
    ]
