# Generated by Django 6.0.1 on 2026-01-11 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_apprelease'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dearlastdigit',
            name='date',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='dearlastthreedigit',
            name='date',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='dearlastthreedigit',
            name='day',
            field=models.CharField(max_length=3),
        ),
        migrations.AlterField(
            model_name='dearlastthreedigit',
            name='evn',
            field=models.CharField(max_length=3),
        ),
        migrations.AlterField(
            model_name='dearlastthreedigit',
            name='mor',
            field=models.CharField(max_length=3),
        ),
        migrations.AlterField(
            model_name='dearlasttwodigit',
            name='date',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='dearlasttwodigit',
            name='day',
            field=models.CharField(max_length=2),
        ),
        migrations.AlterField(
            model_name='dearlasttwodigit',
            name='evn',
            field=models.CharField(max_length=2),
        ),
        migrations.AlterField(
            model_name='dearlasttwodigit',
            name='mor',
            field=models.CharField(max_length=2),
        ),
        migrations.AlterField(
            model_name='singaporelastdigit',
            name='date',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='singaporelastthreedigit',
            name='date',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='singaporelastthreedigit',
            name='day',
            field=models.CharField(max_length=3),
        ),
        migrations.AlterField(
            model_name='singaporelastthreedigit',
            name='evn',
            field=models.CharField(max_length=3),
        ),
        migrations.AlterField(
            model_name='singaporelastthreedigit',
            name='mor',
            field=models.CharField(max_length=3),
        ),
        migrations.AlterField(
            model_name='singaporelasttwodigit',
            name='date',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='singaporelasttwodigit',
            name='day',
            field=models.CharField(max_length=2),
        ),
        migrations.AlterField(
            model_name='singaporelasttwodigit',
            name='evn',
            field=models.CharField(max_length=2),
        ),
        migrations.AlterField(
            model_name='singaporelasttwodigit',
            name='mor',
            field=models.CharField(max_length=2),
        ),
        migrations.CreateModel(
            name='Fax',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('image', models.ImageField(upload_to='fax/')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('date',), name='one_fax_per_day')],
            },
        ),
    ]
