# Generated by Django 6.0.1 on 2026-01-12 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_dearlastdigit_date_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='fax',
            name='one_fax_per_day',
        ),
        migrations.AlterField(
            model_name='dearlastdigit',
            name='date',
            field=models.DateField(unique=True),
        ),
        migrations.AlterField(
            model_name='dearlastdigit',
            name='day',
            field=models.CharField(default='-', max_length=1),
        ),
        migrations.AlterField(
            model_name='dearlastdigit',
            name='evn',
            field=models.CharField(default='-', max_length=1),
        ),
        migrations.AlterField(
            model_name='dearlastdigit',
            name='mor',
            field=models.CharField(default='-', max_length=1),
        ),
        migrations.AlterField(
            model_name='dearlastthreedigit',
            name='date',
            field=models.DateField(unique=True),
        ),
        migrations.AlterField(
            model_name='dearlastthreedigit',
            name='day',
            field=models.CharField(default='-', max_length=3),
        ),
        migrations.AlterField(
            model_name='dearlastthreedigit',
            name='evn',
            field=models.CharField(default='-', max_length=3),
        ),
        migrations.AlterField(
            model_name='dearlastthreedigit',
            name='mor',
            field=models.CharField(default='-', max_length=3),
        ),
        migrations.AlterField(
            model_name='dearlasttwodigit',
            name='date',
            field=models.DateField(unique=True),
        ),
        migrations.AlterField(
            model_name='dearlasttwodigit',
            name='day',
            field=models.CharField(default='-', max_length=2),
        ),
        migrations.AlterField(
            model_name='dearlasttwodigit',
            name='evn',
            field=models.CharField(default='-', max_length=2),
        ),
        migrations.AlterField(
            model_name='dearlasttwodigit',
            name='mor',
            field=models.CharField(default='-', max_length=2),
        ),
        migrations.AlterField(
            model_name='fax',
            name='date',
            field=models.DateField(auto_now_add=True, unique=True),
        ),
        migrations.AlterField(
            model_name='singaporelastdigit',
            name='date',
            field=models.DateField(unique=True),
        ),
        migrations.AlterField(
            model_name='singaporelastdigit',
            name='day',
            field=models.CharField(default='-', max_length=1),
        ),
        migrations.AlterField(
            model_name='singaporelastdigit',
            name='evn',
            field=models.CharField(default='-', max_length=1),
        ),
        migrations.AlterField(
            model_name='singaporelastdigit',
            name='mor',
            field=models.CharField(default='-', max_length=1),
        ),
        migrations.AlterField(
            model_name='singaporelastthreedigit',
            name='date',
            field=models.DateField(unique=True),
        ),
        migrations.AlterField(
            model_name='singaporelastthreedigit',
            name='day',
            field=models.CharField(default='-', max_length=3),
        ),
        migrations.AlterField(
            model_name='singaporelastthreedigit',
            name='evn',
            field=models.CharField(default='-', max_length=3),
        ),
        migrations.AlterField(
            model_name='singaporelastthreedigit',
            name='mor',
            field=models.CharField(default='-', max_length=3),
        ),
        migrations.AlterField(
            model_name='singaporelasttwodigit',
            name='date',
            field=models.DateField(unique=True),
        ),
        migrations.AlterField(
            model_name='singaporelasttwodigit',
            name='day',
            field=models.CharField(default='-', max_length=2),
        ),
        migrations.AlterField(
            model_name='singaporelasttwodigit',
            name='evn',
            field=models.CharField(default='-', max_length=2),
        ),
        migrations.AlterField(
            model_name='singaporelasttwodigit',
            name='mor',
            field=models.CharField(default='-', max_length=2),
        ),
    ]
